stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
  - node_modules/

install:
  stage: install
  script:
  - yarn

build:
  stage: build
  script:
  - yarn build

test:
  stage: test
  script:
  - yarn test

deploy:
  script:
  - mv ./build ./public
  artifacts:
    paths:
    - public
  only:
  - master
