stages:
  - install
  - build
  - test
  - pages

cache:
  paths:
  - node_modules/

install:
  stage: install
  script:
  - yarn

build:
  stage: build
  script:
  - yarn build
  artifacts:
    paths:
    - build

test:
  stage: test
  script:
  - yarn test

pages:
  stage: pages
  script:
  - mv ./public ./public-old
  - mv ./build ./public
  artifacts:
    paths:
    - public
  only:
  - master
