stages:
  - build
  - test
  - deploy

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
  - yarn build

test:
  stage: test
  script:
  - yarn test

deploy:
  script:
  - mv ./build ./public
  artifacts:
    paths:
    - public
  only:
  - master
